### ISSUE TITLE
Add "-" support in seven-segment display

### ISSUE THREAD

**Issue by jdepypere** [janstol/flutter_segment_display#3]
As seen in the [sample image](https://raw.githubusercontent.com/janstol/flutter_segment_display/master/img/displays/seven_segment.png), a dash/minus/hyphen is not supported. Looking at the structure of a seven-segment display this could totally be a valid use case.

Could this be added?

**Comment by janstol** [comment]
Solved in #4. Thanks, @prwater :-)
